# Generated by Django 2.1.7 on 2019-04-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makepages', '0001_initial'),
    ]

    operations = [
    ]
