# Generated by Django 2.1.7 on 2019-04-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makepages', '0002_auto_20190403_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='Something',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
